<?php
/**
 * @copyright (c) 2017 Bourdercloud.com
 * @author Karima Rafes <karima.rafes@bordercloud.com>
 * @link http://www.mediawiki.org/wiki/Extension:LinkedWiki
 * @license CC-by-nc-sa V3.0
 *
 *  Last version : http://github.com/BorderCloud/LinkedWiki
 *
 *
 * This work is licensed under the Creative Commons
 * Attribution-NonCommercial-ShareAlike 3.0
 * Unported License. To view a copy of this license,
 * visit http://creativecommons.org/licenses/by-nc-sa/3.0/
 * or send a letter to Creative Commons,
 * 171 Second Street, Suite 300, San Francisco,
 * California, 94105, USA.
 */

/**
 * This is a backwards-compatibility shim, generated by:
 * https://git.wikimedia.org/blob/mediawiki%2Fcore.git/HEAD/maintenance%2FgenerateJsonI18n.php
 *
 * Beginning with MediaWiki 1.23, translation strings are stored in json files,
 * and the EXTENSION.i18n.php file only exists to provide compatibility with
 * older releases of MediaWiki. For more information about this migration, see:
 * https://www.mediawiki.org/wiki/Requests_for_comment/Localisation_format
 *
 * This shim maintains compatibility back to MediaWiki 1.17.
 */
$messages = array();
if ( !function_exists( 'wfJsonI18nShim87f26c5c106e9dd4' ) ) {
        function wfJsonI18nShim87f26c5c106e9dd4( $cache, $code, &$cachedData ) {
                $codeSequence = array_merge( array( $code ), $cachedData['fallbackSequence'] );
                foreach ( $codeSequence as $csCode ) {
                        $fileName = dirname( __FILE__ ) . "/../i18n/rdfunit/$csCode.json";
                        if ( is_readable( $fileName ) ) {
                                $data = FormatJson::decode( file_get_contents( $fileName ), true );
                                foreach ( array_keys( $data ) as $key ) {
                                        if ( $key === '' || $key[0] === '@' ) {
                                                unset( $data[$key] );
                                        }
                                }
                                $cachedData['messages'] = array_merge( $data, $cachedData['messages'] );
                        }

                        $cachedData['deps'][] = new FileDependency( $fileName );
                }
                return true;
        }

        $GLOBALS['wgHooks']['LocalisationCacheRecache'][] = 'wfJsonI18nShim87f26c5c106e9dd4';
}
